# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Android Firebase App Distribution"
  lane :distribute do
      sh "flutter clean"
      sh "flutter build apk --release --no-tree-shake-icons"
      firebase_app_distribution(
          app: "1:733733637103:android:3ca8784d068906963fc41a",
          firebase_cli_token: ENV["FIREBASE_TOKEN"],
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
          groups: "QA",
          release_notes_file: "../release_notes",
          debug: true
        )
  end
end
